### ISSUE TITLE
GET Request throws - SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by girishsortur** [bulkan/robotframework-requests#101] opened 2016-03-02 11:50 UTC
From the time i have updated robotframework libraries, test scripts written in `.tsv` format fail all the time with the error - `SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)`, though it was working normally earlier. Issue is arising from the `RequestsLibrary` when i am trying to perform a `GET` operation (though create session works fine to authenticate the user before performing GET operation). Here's the full traceback details for the error -

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/RequestsLibrary/RequestsKeywords.py", line 298, in get_request
    session, uri, params, headers, redir, timeout)
  File "/Library/Python/2.7/site-packages/RequestsLibrary/RequestsKeywords.py", line 801, in _get_request
    cookies=self.cookies)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
```

I have following configuration of robot framework libraries -

```
Mac OSX (10.11.3)
Python (2.7.10)
openssl (1.0.2f)
requests (2.9.1)
robotframework (3.0)
robotframework-httplibrary (0.4.2)
robotframework-requests (0.4.4)
robotframework-sshlibrary (2.1.2)
pyOpenSSL (0.15.1)
```

Any help would be appreciated.

**Comment by bulkan** [comment] 2016-03-10 23:14
I'm not sure what the cause of this error is but googling around found this

https://github.com/kennethreitz/requests/issues/2022

Closing this issue as the error seems to be occurring within `requests` and this library

**Closed by bulkan** 2016-03-10 23:14 UTC
Labels: question
