### ISSUE TITLE
Not working with authenticating Proxy

### ISSUE THREAD

**Issue by yahman72** [bulkan/robotframework-requests#40] opened 2014-09-16 08:45 UTC
The RequestsLibrary doesn't work at all behind an authenticating proxy.
The "proxies" setting parameter seems to be ignored.

The GET request is sent directly to the target host, instead of the proxy host
See the "Starting new HTTP connection" entry in the debug log

<pre>
debug log:
==============================================================================
20140916 10:32:15.811 - INFO - +- START TEST: Get Ext Requests [ ]
------------------------------------------------------------------------------
20140916 10:32:15.811 - INFO - +-- START KW: RequestsLibrary.Create Session [ google | http://www.google.com | proxies= {"http": "http://myuser:mypwd@my.proxy.com"} ]
20140916 10:32:15.812 - DEBUG - Creating session: google
20140916 10:32:15.818 - INFO - Argument types are:
<type 'bool'>
20140916 10:32:15.819 - INFO - +-- END KW: RequestsLibrary.Create Session (8)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20140916 10:32:15.819 - INFO - +-- START KW: ${resp} = RequestsLibrary.Get [ google | / ]
20140916 10:32:16.021 - INFO - Starting new HTTP connection (1): www.google.com
20140916 10:34:22.022 - FAIL - ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a perio
d of time, or established connection failed because connected host has failed to respond'))
20140916 10:34:22.022 - DEBUG - Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\RequestsLibrary\keywords.py", line 111, in get
    response = self.get_request(session, uri, headers, params)
  File "c:\Python27\lib\site-packages\RequestsLibrary\keywords.py", line 217, in get_request
    cookies=self.cookies, timeout=self.timeout)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 463, in get
    return self.request('GET', url, **kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 451, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 557, in send
    r = adapter.send(request, **kwargs)
  File "c:\Python27\lib\site-packages\requests\adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
20140916 10:34:22.024 - INFO - +-- END KW: ${resp} = RequestsLibrary.Get (126204)
------------------------------------------------------------------------------
20140916 10:34:22.031 - INFO - +- END TEST: Get Ext Requests (126214)
------------------------------------------------------------------------------

Execution output:
==============================================================================
Get Ext Requests                                                      | FAIL |
ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
------------------------------------------------------------------------------
Json                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================


My env - Windows 7:
> pip list
certifi (14.05.14)
chardet (2.2.1)
contextdecorator (0.10.0)
pip (1.5.6)
PyYAML (3.11)
requests (2.4.1)
robotframework (2.8.5)
robotframework-requests (0.3.7)
setuptools (5.7)
six (1.8.0)
vcrpy (1.0.3)
> python -V
Python 2.7.8

Test case steps:
    Create Session  google  http://www.google.com       proxies= {"http": "http://myuser:mypwd@my.proxy.com"}
    ${resp}=        Get     google                      /
    Should Be Equal As Strings                          ${resp.status_code}     200 
 
</pre>

###################################################################################

I also have a RequestsLibrary running with Jython (2.5.3), and because of v2.5 compatibility I had to use very old libs (requests v0.10.0) and there I got it working (after hacking the requests lib a bit) - The above debug log entries look like this:

NOTE: Here the "Starting new HTTP connection" shows the proxy host
<pre>
20140916 10:20:33.652 - INFO - +-- START TEST: Get Ext Requests [ ]
------------------------------------------------------------------------------
20140916 10:20:33.654 - INFO - +--- START KW: RequestsLibrary.Create Session [ google | http://www.google.com | proxies= {"http": "http://myuser:mypwd@my.proxy.com"} ]
20140916 10:20:33.656 - DEBUG - Creating session: google
20140916 10:20:33.657 - INFO - Argument types are:
<type 'bool'>
20140916 10:20:33.658 - INFO - +--- END KW: RequestsLibrary.Create Session (5)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20140916 10:20:33.660 - INFO - +--- START KW: ${resp} = RequestsLibrary.Get [ google | / ]
20140916 10:20:33.666 - INFO - Starting new HTTP connection (1): my.proxy.com
20140916 10:20:38.570 - INFO - Starting new HTTP connection (1): my.proxy.com
20140916 10:20:38.909 - INFO - ${resp} = <Response [200]>
20140916 10:20:38.910 - INFO - +--- END KW: ${resp} = RequestsLibrary.Get (5249)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20140916 10:20:38.912 - INFO - +--- START KW: BuiltIn.Should Be Equal As Strings [ ${resp.status_code} | 200 ]
20140916 10:20:38.914 - INFO - Argument types are:
<type 'int'>
<type 'unicode'>
20140916 10:20:38.916 - INFO - +--- END KW: BuiltIn.Should Be Equal As Strings (4)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>

**Comment by bulkan** [comment] 2016-01-04 02:09
@vkosuri if you want to look at this issue too please :100:

**Comment by vkosuri** [comment] 2016-01-04 02:24
@bulkan thank you and sure

**Comment by vkosuri** [comment] 2016-01-04 13:41
@yahman72 It seems to working fine with below example, Let me know if you have any issues?

I have installed fallowing packages in my machine.
```
Robotframework == 3.0
Requests == 2.7.8
RequestsKeyowrds == 0.3.9
```

Example

``` Robot
*** Settings ***
Library           RequestsKeywords

*** Test Cases ***
Test case steps:
    ${proxies} =    Evaluate    {"https": "https://www.google.co.in"}
    Create Session    google    http://www.whatismyproxy.com    proxies=${proxies}
    ${resp}=    Get    google    /
    Should Be Equal As Strings    ${resp.status_code}    200
```

``` Shell
>pybot ProxyTest.robot
==============================================================================
ProxyTest
==============================================================================
Test case steps:                                                      | PASS |
------------------------------------------------------------------------------
ProxyTest                                                             | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\vkosuri\output.xml
Log:     C:\Users\vkosuri\og.html
Report:  C:\Users\vkosuri\report.html
```

**Comment by yahman72** [comment] 2016-01-04 14:39
your code has two major mistakes:
1) it's doesn't use a proxy at all:
you set a proxy for http**s** connections and then you open a connection using http --> there's no proxy involved
2) your proxy settings are not for an authenticating proxy (i.e. proxy username + password are missing)

**Comment by vkosuri** [comment] 2016-01-04 14:55
I tried with user name and pass it is working fine. Could try with your example and let me know the output?

``` Robot
Proxy Test case steps:
    ${proxies} =    Evaluate    {"http": "http://malli.kv2:pass@drive.google.com"}
    Create Session  google  http://www.google.com       proxies=${proxies}
    ${resp}=        Get     google                      /
    Should Be Equal As Strings                          ${resp.status_code}     200 
```

``` Shell
C:\Users\malli\Dropbox\Projects\Requests>pybot ProxyTest.robot
==============================================================================
ProxyTest
==============================================================================
Test case steps:                                                      | PASS |
------------------------------------------------------------------------------
Proxy Test case steps:                                                | PASS |
------------------------------------------------------------------------------
ProxyTest                                                             | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  C:\Users\malli\Dropbox\Projects\Requests\output.xml
Log:     C:\Users\malli\Dropbox\Projects\Requests\log.html
Report:  C:\Users\malli\Dropbox\Projects\Requests\report.html
```

**Comment by yahman72** [comment] 2016-01-04 15:21
Unfortunately I'm not anymore behind an authenticating proxy = I cannot test this.

Actually your example code doesn't test the issue at all:
as I wrote: `The "proxies" setting parameter seems to be ignored.The GET request is sent directly to the target host, instead of the proxy host`
i.e. in your example the request is sent directly to "http://www.google.com", if it would be sent to the proxy it would fail, because "http://drive.google.com" is not a proxy. 
In another words you could put anything in the `proxies` variable e.g. `${proxies} =    Evaluate    {"http": "http://not:existing@not.existing.host.com"}` and it would still work...

IMHO: Your really should test with an authenticating proxy, not with dummy google hosts.
If you don't have an authenticating proxy in your company then 
1) set up your own (e.g. you might get http://www.squid-cache.org/ working on your own PC as authenticating proxy)
or
2) trace the HTTP traffic with wireshark and verify that the requests are really sent to the proxy first.

**Comment by vkosuri** [comment] 2016-01-06 01:10
@yahman72 Thank you very much, I have tried without auth it went fine.

Below is my test script

``` Robot
*** Settings ***
Library           RequestsKeywords

*** Test Cases ***
Proxy case steps:
    ${proxies} =    Evaluate    {'http' : 'http://10.59.57.201:5000/'}
    Create Session    proxy    http://my-pc.org    proxies=${proxies}   debug=1
    ${resp}=    Get    proxy    /#
    Log     ${resp.text}
    Log     ${resp.status_code}
    Should Be Equal As Strings    ${resp.status_code}    200
```
A sample screen shot of response

![proxyinfo](https://cloud.githubusercontent.com/assets/13664257/12132193/778ebc3a-b43f-11e5-997d-45870fa6361a.png)

And also the error was listed above snippet

```
ConnectionError: ('Connection aborted.', error(10060,
```
**This behavior may occur when the Web Proxy service connection settings do not allow enough time to receive a response from the destination Web site before the service closes the connection.**

By default, the Web Proxy service **waits for 60 seconds** on initial connection attempts to a Web site and all later "GET" requests for a response from the server, and it waits 120 seconds before it times out idle socket connections.

More information available https://support.microsoft.com/en-us/kb/811087

**Comment by vkosuri** [comment] 2016-01-10 03:23
@yahman72 any updates?

**Comment by yahman72** [comment] 2016-01-11 05:15
you are again testing without proxy authentication, there's no problem with that (see my original post).

**Comment by vkosuri** [comment] 2016-01-27 09:54
@yahman72 I apologies, I didn't find any concrete example to reproduce this issue, If you find similar type issue with latest code changes please create another issue

If you are satisfied, could you please close this issue?

**Closed** 2016-01-31 10:21 UTC
Labels: accepted

**Comment by yahman72** [comment] 2016-02-02 05:11
sorry for the late reply, I was offline for a couple of days.

Just a quick note on this:
I don't see any results with authenticating proxy, only proxy-requests without authentication. So it might be that it's still not working.
Closing this is fine with me, because I don't have access to an environment that has an authenticating proxy.

**Comment by bbuzens** [comment] 2021-02-24 12:15
On Windows 7, using a proxy to access internet 
*requests* seems to use badly the system configuration
therefore *robotfralework-requests* doesn't pass *proxies* value well

My configuration 

```
requests==2.25.1
robotframework==3.2.2
robotframework-requests==0.8.1
robotframework-sshlibrary==3.6.0
```

To [force requests proxy configuration](https://requests.readthedocs.io/en/master/user/advanced/#proxies) by passing arguments to the *get* method

```python
import requests

proxies = {
  'http': 'http://localhost:53128',
  'https': 'http://localhost:53128',
}

response= requests.get('http://example.org').status_code
print(response)

try:
    response = requests.get('https://www.google.com').status_code
except requests.exceptions.ProxyError:
    print("Proxy error is catched")

response = requests.get('https://www.google.com', proxies=proxies).status_code
print(response)
```

There the output

```
200
Proxy error catched
200

Process finished with exit code 0
```

So, i created an analog request in *RobotFramework* 

```
*** Settings ***
Library                 Collections
Library                 RequestsLibrary
Library                 BuiltIn
Suite Setup             Create Session    Google            https://www.google.com      proxies={'http': 'http://localhost:3128', 'https': 'http://localhost:3128',}
Suite Teardown          Delete All Sessions

*** Variables ***


*** Test Cases ***

Get Google service
    ${resp}=   HEAD On Session          Google           /           expected_status=200
    Should Be Equal As Strings          ${resp.reason}          OK
```

But i still got the *ProxyError*

```
Get Google service                                                    [ WARN ] Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))': /
[ WARN ] Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))': /
[ WARN ] Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))': /
| FAIL |
ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)))
```

There is probably something wrong in the *robotframework-requests* library


> PS
> Running the tests inside a Linux container with a proper sytem configuration of proxy without any *proxies* value for *requests* is passing

**Comment by lucagiove** [comment] 2021-02-24 22:49
Hi can you try to use the 0.8 version and add the proxies parameter to `GET On Session` keyword?
Or you can install the 0.9 pre-release and try `GET` session less keyword with proxy settings and let me know.

Thank you,
Luca

**Comment by bbuzens** [comment] 2021-03-12 10:50
It still raise the same error.

My new configuration :
```
>pip freeze
certifi==2020.12.5
chardet==4.0.0
idna==2.10
requests==2.25.1
robotframework==4.0
robotframework-requests==0.9a3
urllib3==1.26.3
```

*requests* is working but *robotframework-requests* doesn't.

**Comment by lucagiove** [comment] 2021-03-12 11:28
Ok, I might have to look at it could you open a new issue since this is closed?

**Comment by bbuzens** [comment] 2021-03-12 11:30
With a better analysis, i figured it might be a *requests* issue.

*requests* works well if you define the proxy in a *get* command 
```python
session = requests.sessions.Session()
session_response = session.get('https://www.google.com', proxies=proxies).status_code
print(session_response)
```

Returns  `200`

But, if you're managing proxies as defined in the [*requests* documentation](https://requests.readthedocs.io/en/master/user/advanced/#proxies)
```python
session_with_proxies = requests.sessions.Session()
session_with_proxies.proxies.update(proxies)
print(session_with_proxies.proxies)
try:
    session_with_proxies_response = session.get('https://www.google.com').status_code
except requests.exceptions.ProxyError:
    print("Proxy error catched")
```

You raise en error like this
```
{'http': 'http://localhost:53128', 'https': 'http://localhost:53128', 'ftp': 'ftp://localhost:53128'}
Proxy error catched
```

So, a right way to pass proxy parameters to any get or head function using a session is 
```robotframework
*** Settings ***
Library                 Collections
Library                 RequestsLibrary
Library                 BuiltIn
Suite Setup             Create Session    app_service               https://${APP_SERVICE}:${APP_PORT}
Suite Teardown          Delete All Sessions

*** Variables ***

${APP_SERVICE}=         www.google.com
${APP_PORT}=            443
&{proxies}=             http=http://localhost:53128         https=http://localhost:53128

*** Test Cases ***
Log Proxies
    log        ${proxies}
    SHOULD CONTAIN      ${proxies.http}      localhost
    SHOULD CONTAIN      ${proxies.https}      localhost

Head Google
    ${resp}=   HEAD On Session          app_service           /     proxies=${proxies}           expected_status=200
    Should Be Equal As Strings          ${resp.reason}          OK

Get Google
    ${resp}=   Get On Session           app_service           /     proxies=${proxies}           expected_status=200
    Should Be Equal As Strings          ${resp.reason}          OK

```

**Comment by bbuzens** [comment] 2021-03-15 08:29
For your information, an issue is opened on requests :
https://github.com/psf/requests/issues/5772#issue-830110982
